[package]
name = "cider"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.46", features = ["derive"] }
dirs = "6.0.0"
plist = "1.7.4"
serde = { version = "1.0.219", features = ["derive"] }
